# Generated by Django 4.2.3 on 2025-02-20 20:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('idioma', models.CharField(max_length=100)),
                ('duracao', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cursosidiomas.usuario')),
                ('matricula', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cursosidiomas.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cursosidiomas.usuario')),
                ('cursos_ministrados', models.ManyToManyField(blank=True, related_name='professores', to='cursosidiomas.curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('cursosidiomas.usuario',),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('duracao', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursosidiomas.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horario', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorias_solicitadas', to='cursosidiomas.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='cursosidiomas.professor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursosidiomas.professor'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='cursosidiomas.curso')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='cursosidiomas.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='aulas_assistidas',
            field=models.ManyToManyField(blank=True, related_name='alunos_assistiram', to='cursosidiomas.aula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos_inscritos',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='cursosidiomas.curso'),
        ),
    ]
